# gen_pincat.py
#
# runs dxcat for series of parameter files generated by gen_params.py
# 
# Mai Le 05/24/16
# cleaned up 05/18/17

import subprocess
import array
import smtplib
import time
import os.path

## set up text notification by sending email
#smtpObj = smtplib.SMTP_SSL('smtp.gmail.com', 465)
#smtpObj.login('dummysender@gmail.com', 'pswd')

# Nframes and resp_vals must match those used by gen_params.py
Nframes = 20
resp_vals = [x / 10.0 for x in range(0, 11, 1)]

for resp_val in resp_vals :
	for frame in range(0, Nframes) :
                start = time.time()
        	resp_file = '/y/mtle/resp_pincat/pincat_resp' + str(resp_val) + '_frame' + str(frame)
		par_file = '/y/mtle/resp_pincat/par/pincat_resp' + str(resp_val) + '_frame' + str(frame) + '.par'
                if not os.path.isfile(par_file) :
                        print(par_file, 'not found')
                call = './dxcat2', par_file, resp_file
                print call
	        subprocess.call(call) 
                print time.time() - start, 'seconds to generate one resp phase'

## send text when done
#smtpObj.sendmail('dummysender@gmail.com', 'phonenumber@provider.net', 'done with PINCAT')
#smtpObj.quit()
